"""Added quiz tables

Revision ID: 00ce72110a76
Revises: 49918fdd2512
Create Date: 2021-04-27 19:40:11.029730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ce72110a76'
down_revision = '49918fdd2512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizname', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questiontext', sa.String(length=256), nullable=True),
    sa.Column('quizId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answertext', sa.String(length=256), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=False),
    sa.Column('correctAnswer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizid', sa.Integer(), nullable=False),
    sa.Column('userresultid', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quizid'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['userresultid'], ['user_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_result')
    op.drop_table('answer')
    op.drop_table('user_result')
    op.drop_table('question')
    op.drop_table('quiz')
    # ### end Alembic commands ###
