"""Added topics table

Revision ID: 7884a10f58b2
Revises: 00ce72110a76
Create Date: 2021-05-04 12:47:04.948735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7884a10f58b2'
down_revision = '00ce72110a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizid', sa.Integer(), nullable=True),
    sa.Column('topicname', sa.String(length=256), nullable=True),
    sa.Column('topiccontent', sa.String(length=1024), nullable=True),
    sa.Column('topicvideolink', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['quizid'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###
